version: '3'
services:
	app:
	    build: app
	    restart: always
	    logging:
	           driver: "json-file"
	           options:
		max-size:"1600m"
	    
	nginx:
	    build: ngnix
	    restart: always
	    ports:
	          - 80:80
